// show_json(character)
export const characterProxy = {
	"x": 63.428132355972664,
	"y": 794.9774215413523,
	"note": "This is a proxy object, the real character is in parent.character",
	"properties": [
		"x",
		"y",
		"_events",
		"_eventsCount",
		"tempDisplayObjectParent",
		"transform",
		"alpha",
		"visible",
		"renderable",
		"parent",
		"worldAlpha",
		"filterArea",
		"_filters",
		"_enabledFilters",
		"_bounds",
		"_boundsID",
		"_lastBoundsID",
		"_boundsRect",
		"_localBoundsRect",
		"_mask",
		"_destroyed",
		"children",
		"_anchor",
		"_texture",
		"_width",
		"_height",
		"_tint",
		"_tintRGB",
		"blendMode",
		"shader",
		"cachedTint",
		"_textureID",
		"_textureTrimmedID",
		"vertexData",
		"vertexTrimmedData",
		"_transformID",
		"_transformTrimmedID",
		"pluginName",
		"roundPixels",
		"cskin",
		"i",
		"j",
		"skin",
		"stype",
		"updates",
		"cscale",
		"in",
		"map",
		"hp",
		"max_hp",
		"mp",
		"max_mp",
		"xp",
		"attack",
		"heal",
		"frequency",
		"speed",
		"range",
		"armor",
		"resistance",
		"level",
		"rip",
		"afk",
		"s",
		"c",
		"q",
		"age",
		"pdps",
		"id",
		"cid",
		"cx",
		"slots",
		"ctype",
		"owner",
		"int",
		"str",
		"dex",
		"vit",
		"for",
		"mp_cost",
		"mp_reduction",
		"max_xp",
		"goldm",
		"xpm",
		"luckm",
		"isize",
		"esize",
		"gold",
		"cash",
		"targets",
		"m",
		"evasion",
		"miss",
		"reflection",
		"lifesteal",
		"manasteal",
		"rpiercing",
		"apiercing",
		"crit",
		"critdamage",
		"dreturn",
		"tax",
		"xrange",
		"pnresistance",
		"firesistance",
		"fzresistance",
		"phresistance",
		"stresistance",
		"incdmgamp",
		"stun",
		"blast",
		"explosion",
		"courage",
		"mcourage",
		"pcourage",
		"fear",
		"items",
		"cc",
		"ipass",
		"home",
		"friends",
		"acx",
		"xcx",
		"emx",
		"pzazz",
		"last_ms",
		"cxc",
		"name",
		"displayGroup",
		"parentGroup",
		"walking",
		"animations",
		"fx",
		"emblems",
		"real_alpha",
		"real_x",
		"real_y",
		"type",
		"me",
		"base",
		"awidth",
		"aheight",
		"explanation",
		"ping",
		"vision",
		"ntag_cache",
		"name_tag",
		"last_fear",
		"_activeParentLayer",
		"updateOrder",
		"zOrder",
		"displayOrder",
		"stats",
		"bank",
		"from_x",
		"from_y",
		"going_x",
		"going_y",
		"moving",
		"ref_speed",
		"vx",
		"vy",
		"angle",
		"a_direction",
		"direction",
		"ms_walk",
		"last_stop",
		"last_walking",
		"listeners",
		"on",
		"code",
		"move_num",
		"target",
		"focus",
		"a_angle",
		"_onTextureUpdate",
		"_onAnchorUpdate",
		"calculateVertices",
		"calculateTrimmedVertices",
		"_renderWebGL",
		"_renderCanvas",
		"_calculateBounds",
		"getLocalBounds",
		"containsPoint",
		"destroy",
		"setTexture",
		"onChildrenChange",
		"addChild",
		"addChildAt",
		"swapChildren",
		"getChildIndex",
		"setChildIndex",
		"getChildAt",
		"removeChild",
		"removeChildAt",
		"removeChildren",
		"updateTransform",
		"calculateBounds",
		"renderWebGL",
		"renderAdvancedWebGL",
		"renderCanvas",
		"containerUpdateTransform",
		"getChildByName",
		"containerRenderWebGL",
		"containerRenderCanvas",
		"_recursivePostUpdateTransform",
		"getBounds",
		"toGlobal",
		"toLocal",
		"setParent",
		"setTransform",
		"displayObjectUpdateTransform",
		"_cacheAsBitmap",
		"_cacheData",
		"_renderCachedWebGL",
		"_initCachedDisplayObject",
		"_renderCachedCanvas",
		"_initCachedDisplayObjectCanvas",
		"_calculateCachedBounds",
		"_getCachedLocalBounds",
		"_destroyCachedDisplayObject",
		"_cacheAsBitmapDestroy",
		"getGlobalPosition",
		"accessible",
		"accessibleTitle",
		"accessibleHint",
		"tabIndex",
		"_accessibleActive",
		"_accessibleDiv",
		"interactive",
		"interactiveChildren",
		"hitArea",
		"buttonMode",
		"cursor",
		"trackedPointers",
		"_trackedPointers",
		"generateTexture",
		"parentLayer",
		"zIndex",
		"layerableChildren",
		"eventNames",
		"emit",
		"once",
		"removeListener",
		"removeAllListeners",
		"off",
		"addListener",
		"setMaxListeners",
		"user"
	],
	"read_only": [
		"x",
		"y",
		"real_x",
		"real_y",
		"from_x",
		"from_y",
		"going_x",
		"going_y",
		"moving",
		"target",
		"vx",
		"vy",
		"move_num",
		"attack",
		"speed",
		"hp",
		"mp",
		"xp",
		"max_hp",
		"max_mp",
		"range",
		"level",
		"rip",
		"s",
		"c",
		"in",
		"map",
		"stand",
		"items",
		"slots",
		"on",
		"once"
	],
	"proxy_character": true,
	"alpha": 1,
	"visible": true,
	"cskin": "11",
	"i": 1,
	"j": 1,
	"skin": "fpriest",
	"stype": "full",
	"updates": 6281,
	"cscale": 2,
	"in": "main",
	"map": "main",
	"hp": 1860,
	"max_hp": 1860,
	"mp": 1235,
	"max_mp": 1260,
	"xp": 558067,
	"attack": 76,
	"heal": 190,
	"frequency": 0.6389358304297328,
	"speed": 50,
	"range": 170,
	"armor": 21,
	"resistance": 72,
	"level": 39,
	"rip": false,
	"afk": false,
	"s": {
		"mluck": {
			"ms": 3279840,
			"f": "Bjarnu"
		},
		"newcomersblessing": {
			"ms": 1682687,
			"f": "Schnu",
			"undefined": 0
		}
	},
	"c": {},
	"q": {},
	"age": 998,
	"pdps": 4416.328,
	"id": "Priestesther",
	"cid": 265,
	"cx": {},
	"slots": {
		"ring1": null,
		"ring2": {
			"name": "ringsj",
			"level": 1
		},
		"earring1": null,
		"earring2": null,
		"belt": {
			"name": "hpbelt",
			"level": 1
		},
		"mainhand": {
			"name": "staff",
			"gift": 1,
			"level": 0
		},
		"offhand": null,
		"helmet": {
			"name": "helmet",
			"gift": 1,
			"level": 0
		},
		"chest": null,
		"pants": null,
		"shoes": {
			"name": "shoes",
			"gift": 1,
			"level": 0
		},
		"gloves": null,
		"amulet": null,
		"orb": null,
		"elixir": null,
		"cape": null
	},
	"ctype": "priest",
	"owner": "6610660251664384",
	"int": 51,
	"str": 11,
	"dex": 12,
	"vit": 19,
	"for": 3,
	"mp_cost": 25,
	"mp_reduction": 0,
	"max_xp": 580000,
	"goldm": 1.1,
	"xpm": 1.1,
	"luckm": 1.22,
	"isize": 42,
	"esize": 33,
	"gold": 328996,
	"cash": 0,
	"targets": 1,
	"m": 0,
	"evasion": 0,
	"miss": 0,
	"reflection": 0,
	"lifesteal": 0,
	"manasteal": 0,
	"rpiercing": 0,
	"apiercing": 0,
	"crit": 0,
	"critdamage": 0,
	"dreturn": 0,
	"tax": 0.04,
	"xrange": 25,
	"pnresistance": 0,
	"firesistance": 0,
	"fzresistance": 0,
	"phresistance": 0,
	"stresistance": 0,
	"incdmgamp": 0,
	"stun": 0,
	"blast": 0,
	"explosion": 0,
	"courage": 2,
	"mcourage": 7,
	"pcourage": 2,
	"fear": 0,
	"items": [
		{
			"q": 17,
			"name": "seashell"
		},
		{
			"q": 3,
			"name": "crabclaw"
		},
		{
			"q": 4,
			"name": "candypop"
		},
		{
			"name": "wcap",
			"level": 0
		},
		{
			"name": "ringsj",
			"level": 0
		},
		{
			"name": "hpamulet",
			"level": 0
		},
		{
			"name": "ringsj",
			"level": 0
		},
		{
			"q": 4,
			"name": "beewings"
		},
		{
			"q": 1,
			"name": "gslime"
		},
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null
	],
	"cc": 4,
	"ipass": "iwt9e3EeZE28",
	"home": "EUI",
	"friends": [],
	"acx": {},
	"xcx": [
		"fpriest",
		"mpriest",
		"marmor12e",
		"mbody5g",
		"hairdo402",
		"makeup105",
		"makeup117",
		"mmakeup00",
		"fmakeup01",
		"fmakeup02",
		"fmakeup03",
		"marmor12c",
		"mbody5e"
	],
	"emx": {},
	"pzazz": 0,
	"last_ms": "2022-10-11T19:19:23.821Z",
	"name": "Priestesther",
	"walking": null,
	"fx": {
		"aaa": null,
		"attack": null
	},
	"emblems": {},
	"real_alpha": 1,
	"real_x": 63.428132355972664,
	"real_y": 794.9774215413523,
	"type": "character",
	"me": 1,
	"base": {
		"h": 8,
		"v": 7,
		"vn": 2
	},
	"awidth": 26,
	"aheight": 34,
	"explanation": "Hey Adventurer! This is your very own character that is a PIXI.Sprite Object. Adventure Land uses PIXI to draw things. You can learn more about it: https://www.pixijs.com/ and draw your own stuff via CODE! (Technical) Since your character is a special object, it doesn't get drawn like other entities, therefore your real character object has static x and y values. The character object in Code is an Object that mimics and extends your actual character Object. It's kinda complicated, but the only difference is that your real character object has different x and y values.",
	"ping": 61.025,
	"vision": [
		700,
		500
	],
	"ntag_cache": "Priestesther|undefined|false|false|false|false|false|false|true",
	"name_tag": {
		"x": 0,
		"y": 0,
		"width": 1,
		"height": 1,
		"alpha": 1,
		"visible": true,
		"zy": -999999999999999,
		"name": null
	},
	"last_fear": 0,
	"stats": {
		"str": 11,
		"dex": 12,
		"int": 51,
		"vit": 19,
		"for": 3
	},
	"from_x": 63.428132355972664,
	"from_y": 744.9774215413523,
	"going_x": 63.428132355972664,
	"going_y": 794.9774215413523,
	"moving": false,
	"ref_speed": 50,
	"vx": 0,
	"vy": 0,
	"angle": -171.80268548009693,
	"a_direction": 1,
	"direction": 1,
	"ms_walk": "2022-10-11T19:19:21.537Z",
	"last_stop": "2022-10-11T19:19:21.574Z",
	"last_walking": 133,
	"listeners": [
		{
			"id": "he5B6CLN4qMXXKOhTO7W4ciHsW8mcg",
			"event": "stacked"
		},
		{
			"id": "KAfyPHkfBQLtsxDx7AXKO7U6K7x9TG",
			"event": "death"
		},
		{
			"id": "lA6yu76DeN6bnrHDTMxNieSaVnnVdA",
			"event": "cm",
			"one": true
		}
	],
	"code": false,
	"move_num": 31692496,
	"target": "4867833",
	"focus": null,
	"a_angle": -171.80268548009693,
	"bot": ""
}